name: Azure Deployment

on:
  push:
    branches:
      - main

jobs:
  backend:
    name: Deploy Backend (ASP.NET Core)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Build and publish
        run: |
          cd ECommerceApp
          dotnet restore
          dotnet build --configuration Release
          dotnet publish -c Release -o publish

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ECommerceApp/publish

  frontend:
    name: Deploy Frontend (React)
    runs-on: ubuntu-latest
    needs: backend

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install and Build
        run: |
          cd ecommercefrontend
          npm install
          echo "REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL }}" >> .env.production
          npm run build

      - name: Deploy to Azure Static Web App
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATICWEBAPP_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "ecommercefrontend"
          output_location: "build"
